import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { formatMoney } from "@/lib/domain/pricing";
import { ProgressEditor } from "@/components/progress-editor";

export default async function ApprovedEstimate({params}:{params:Promise<{id:string}>}){
  const {id}=await params;const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
  const {data:membership}=await supabase.from("company_memberships").select("company_id,role").eq("user_id",user.id).eq("status","active").limit(1).single();if(!membership)redirect("/dashboard");
  const [{data:estimate},{data:snapshot},{data:progress}]=await Promise.all([
    supabase.from("estimates").select("id,title,status,estimate_number,total_cents,approved_at,formula_version").eq("id",id).eq("company_id",membership.company_id).single(),
    supabase.from("estimate_approval_snapshots").select("snapshot,snapshot_hash").eq("estimate_id",id).maybeSingle(),
    supabase.from("estimate_progress").select("status,completion_percent,progress_notes").eq("estimate_id",id).maybeSingle(),
  ]);if(!estimate)notFound();if(estimate.status==="draft")redirect(`/dashboard/estimates/${id}/edit`);
  const approved=snapshot?.snapshot as {rooms?:Array<{name:string;length:string;width:string;height:string;workers:string;wageDollars:string;prepHours:string;paint?:{brandName?:string;colorCode?:string;colorName?:string;productName?:string};result?:{netPaintableAreaSqFt?:number;paintCostCents?:number}}> }|undefined;
  return <main className="min-h-screen"><header className="border-b bg-surface print:hidden"><div className="mx-auto max-w-5xl px-5 py-4"><Link href="/dashboard/estimates?tab=approved" className="font-semibold text-brand">← Approved</Link></div></header><div className="mx-auto max-w-5xl space-y-6 px-5 py-8"><section className="rounded-xl bg-[#16251d] p-6 text-white"><p className="text-xs uppercase text-emerald-100/70">Approved Estimate #{estimate.estimate_number}</p><h1 className="mt-2 text-3xl font-semibold">{estimate.title}</h1><p className="mt-4 font-mono text-3xl">{formatMoney(estimate.total_cents)}</p><p className="mt-2 text-sm text-emerald-100/70">Formula {estimate.formula_version} · Locked {estimate.approved_at?new Date(estimate.approved_at).toLocaleString():""}</p></section><section className="rounded-xl border bg-surface p-5"><h2 className="text-xl font-semibold">Locked Scope and Pricing</h2><p className="mt-1 text-sm text-muted">Measurements, labor assumptions, paint, and pricing are preserved from the approval snapshot.</p><div className="mt-4 space-y-3">{approved?.rooms?.map((room,index)=><article key={`${room.name}-${index}`} className="rounded-lg bg-background p-4"><h3 className="font-semibold">{room.name}</h3><p className="mt-1 text-sm">{room.length} × {room.width} × {room.height} ft · {room.result?.netPaintableAreaSqFt??0} ft² net</p><p className="text-sm text-muted">{room.paint?.brandName} {room.paint?.colorCode} {room.paint?.colorName} · {room.paint?.productName}</p></article>)}</div><p className="mt-4 break-all text-xs text-muted">Snapshot integrity: {snapshot?.snapshot_hash}</p></section>{progress&&<ProgressEditor estimateId={id} initialStatus={progress.status} initialPercent={progress.completion_percent} initialNotes={progress.progress_notes??""}/>}<p className="print:hidden text-sm text-muted">Use your browser’s Print command to print or save this immutable approved estimate as PDF.</p></div></main>;
}
