begin;
set local search_path = public, extensions;
select plan(35);
select has_table('public','estimate_approval_snapshots','approval snapshots exist');
select has_table('public','estimate_status_history','status history exists');
select has_table('public','room_openings','normalized room openings exist');
select has_column('public','room_openings','subtract_from_paintable_area','openings support optional deductions');
select has_column('public','estimates','deleted_at','draft soft deletion is available');
select has_column('public','estimate_rooms','surface_type','rooms store a stable surface type key');
select has_column('public','estimate_rooms','surface_modifier_snapshot','rooms snapshot the approved surface modifier');
select has_column('public','estimates','number_of_workers','estimates snapshot shared worker count');
select has_column('public','estimates','average_hourly_wage_cents','estimates snapshot shared hourly wage');
select has_column('public','estimates','prep_person_hours_per_room','estimates snapshot prep person-hours per room');
select has_index('public','estimate_status_history','estimate_status_history_estimate_changed_idx','history lookup is indexed');
select policies_are('public','estimate_status_history',array['estimate_history_insert','estimate_history_read'],'history has only scoped read and insert policies');
select has_column('public','estimates','other_direct_materials_cents','legacy other-materials values remain readable');
select policy_cmd_is('public','audit_logs','audit_logs_insert_authorized','INSERT','authorized draft audit insert policy exists');
select has_function('public','delete_estimate_draft',array['uuid','text'],'manager draft deletion RPC exists');
select has_table('public','estimate_progress','estimate progress exists');
select has_table('public','room_progress','room progress exists');
select has_table('public','company_estimate_settings','company estimate settings exist');
select has_column('public','company_estimate_settings','average_hourly_pay_cents','average pay uses integer cents');
select has_column('public','company_estimate_settings','project_overhead_percent','company overhead default is persisted');
select col_default_is('public','company_estimate_settings','project_overhead_percent','15','company overhead defaults to 15 percent');
select has_column('public','room_progress','is_completed','room completion is persisted');
select has_column('public','room_progress','completed_at','room completion timestamp is persisted');
select has_column('public','room_progress','completed_by','room completion actor is persisted');
select has_function('public','set_room_completion_status',array['uuid','boolean'],'narrow room completion RPC exists');
select has_function('public','update_company_estimate_settings',array['uuid','bigint','numeric'],'manager settings RPC exists');
select has_table('public','retailer_data_sources','retailer sources exist');
select has_table('public','retailer_import_jobs','retailer jobs exist');
select has_index('public','estimates','estimates_company_status_updated_idx','draft/approved list index exists');
select is((select count(*)::integer from public.retailer_data_sources s join public.paint_retailers r on r.id=s.retailer_id where r.slug='lowes'),1,'Lowe''s source is separate');
select is((select count(*)::integer from public.retailer_data_sources s join public.paint_retailers r on r.id=s.retailer_id where r.slug='home-depot'),1,'Home Depot source is separate');
select has_column('public','profiles','estimate_tutorial_completed_at','estimate tutorial completion timestamp is stored');
select has_column('public','profiles','estimate_tutorial_version','estimate tutorial completion is versioned');
select has_function('public','complete_estimate_tutorial',array['integer'],'authenticated tutorial completion RPC exists');
select has_trigger('public','estimates','reject_tutorial_estimate_persistence','tutorial estimates cannot be persisted');
select * from finish();
rollback;
