import Link from "next/link";
import { ArrowRight, Calculator, Check, Clock3, Gauge, PaintBucket, Ruler, ShieldCheck, Sparkles, Users } from "lucide-react";

const process=[["01","Enter room dimensions","Capture the room, walls, windows, and doors."],["02","Select paint and materials","Make coverage rate, coats, containers, and pricing explicit."],["03","Configure labor and margin","Separate hours, crew duration, burden, overhead, and gross margin."],["04","Generate the estimate","Review contractor cost, customer price, profit, and assumptions."]];
const benefits=[[Clock3,"Estimate faster","Move from takeoff to an explainable price without rebuilding spreadsheets."],[PaintBucket,"Reduce material mistakes","Subtract openings and round up to purchasable paint quantities."],[Gauge,"Price consistently","Use the same margin and cost formula for every estimate."],[Users,"Plan the crew","Keep total labor hours separate from elapsed crew duration."],[ShieldCheck,"Protect profit","See wages, burden, overhead, and expected gross profit before presenting price."],[Calculator,"Present professionally","Create a clear calculation snapshot ready for customer workflows."]];

export default function Home(){return <main className="overflow-hidden">
 <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6"><Link href="/" className="text-xl font-bold"><span className="text-brand">Smart</span>Coat</Link><div className="flex items-center gap-3"><Link href="/tour" className="hidden text-sm font-semibold sm:block">Take a Tour</Link><Link href="/login" className="rounded-lg border border-border bg-surface px-4 py-2 text-sm font-semibold">Sign in</Link></div></nav>
 <section className="mx-auto grid max-w-7xl items-center gap-14 px-6 py-16 lg:grid-cols-[1.05fr_.95fr] lg:py-24"><div><p className="mb-5 inline-flex rounded-full bg-emerald-100 px-3 py-1 text-sm font-semibold text-brand-dark">Estimating software for painting contractors</p><h1 className="text-5xl font-semibold leading-[1.02] tracking-[-.055em] sm:text-7xl">Estimate faster. Price accurately. <span className="text-brand">Protect your profit.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted">Calculate paint quantities, estimated material costs, labor requirements, crew duration, target margin, and a customer-ready price with every assumption visible.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/login?mode=signup" className="inline-flex min-h-12 items-center gap-2 rounded-lg bg-brand px-5 font-semibold text-white">Start Estimating<ArrowRight size={18}/></Link><Link href="/tour" className="inline-flex min-h-12 items-center gap-2 rounded-lg border border-border bg-surface px-5 font-semibold"><Sparkles size={18}/>Take a Tour</Link></div><p className="mt-4 text-xs text-muted">Tour calculations are isolated demo data. No payment is collected without confirmation.</p></div>
 <div className="rounded-3xl bg-[#16251d] p-6 text-white shadow-2xl shadow-emerald-950/20 sm:p-8"><div className="flex justify-between"><span className="text-sm text-emerald-100/70">Living Room Estimate</span><span className="rounded-full bg-emerald-300/10 px-3 py-1 text-xs text-emerald-200">Formula v2.0</span></div><div className="mt-8 grid grid-cols-3 gap-2 text-center"><Preview l="Gross walls" v="432 ft²"/><Preview l="Windows" v="−32 ft²"/><Preview l="Paintable" v="400 ft²"/></div><div className="my-6 h-px bg-white/10"/><dl className="space-y-3 text-sm"><Row l="Paint · 2.25 gal" v="$107.96"/><Row l="Labor + burden" v="$197.12"/><Row l="Overhead" v="$30.51"/><Row l="Contractor cost" v="$335.59"/></dl><div className="mt-6 rounded-xl bg-emerald-300/10 p-5"><p className="text-xs text-emerald-100/60">Recommended customer price · 45% margin</p><p className="mt-1 font-mono text-4xl">$610.16</p></div></div></section>
 <section className="border-y border-border bg-surface py-20"><div className="mx-auto max-w-7xl px-6"><p className="text-sm font-bold uppercase tracking-widest text-brand">How SmartCoat works</p><h2 className="mt-3 max-w-2xl text-4xl font-semibold tracking-tight">From room dimensions to a defendable price.</h2><div className="mt-10 grid gap-5 md:grid-cols-4">{process.map(([n,t,c])=><article key={n} className="rounded-xl border border-border p-5"><span className="font-mono text-sm text-brand">{n}</span><h3 className="mt-7 font-semibold">{t}</h3><p className="mt-2 text-sm leading-6 text-muted">{c}</p></article>)}</div></div></section>
 <section className="mx-auto max-w-7xl px-6 py-20"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-sm font-bold uppercase tracking-widest text-brand">Built for the estimate handoff</p><h2 className="mt-3 text-4xl font-semibold tracking-tight">Clear inputs. Consistent outputs.</h2><p className="mt-5 leading-7 text-muted">SmartCoat currently provides deterministic, rule-based calculations and warnings. Historical learning and live retailer feeds are future integrations—not claims hidden behind basic arithmetic.</p></div><div className="grid gap-4 sm:grid-cols-2">{benefits.map(([Icon,title,copy])=>{const I=Icon as typeof Ruler;return <article key={String(title)} className="rounded-xl bg-surface p-5"><I className="text-brand"/><h3 className="mt-4 font-semibold">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-muted">{String(copy)}</p></article>})}</div></div></section>
 <section className="bg-[#16251d] py-20 text-white"><div className="mx-auto grid max-w-7xl gap-12 px-6 lg:grid-cols-2"><div><p className="text-sm font-bold uppercase tracking-widest text-emerald-300">SmartCoat Premium</p><h2 className="mt-3 text-4xl font-semibold tracking-tight">Unlock the full painting workflow.</h2><p className="mt-5 leading-7 text-emerald-100/70">Premium enables real saved estimates, customer and project workflows, consistent pricing snapshots, and the operational foundation for crews, reporting, exports, and integrations as those modules ship.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/subscribe" className="inline-flex min-h-12 items-center rounded-lg bg-emerald-400 px-5 font-semibold text-emerald-950">Subscribe to SmartCoat Premium</Link><Link href="/tour" className="inline-flex min-h-12 items-center rounded-lg border border-white/20 px-5 font-semibold">Take a Tour</Link></div></div><div className="grid gap-3 sm:grid-cols-2">{["Unlimited real estimates","Saved calculation snapshots","Customer and project records","Crew and duration planning","Margin and cost controls","Premium workflow access"].map(x=><div key={x} className="flex gap-3 rounded-lg bg-white/5 p-4"><Check className="text-emerald-300" size={18}/><span>{x}</span></div>)}</div></div></section>
 </main>}
function Preview({l,v}:{l:string;v:string}){return <div className="rounded-lg bg-white/5 p-3"><p className="text-[11px] text-emerald-100/60">{l}</p><p className="mt-1 font-mono font-semibold">{v}</p></div>}
function Row({l,v}:{l:string;v:string}){return <div className="flex justify-between"><dt>{l}</dt><dd className="font-mono">{v}</dd></div>}
