"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, Sparkles, X } from "lucide-react";
import { paintGallons } from "@/lib/domain/measurements";

const features=[["Dashboard","Pipeline, workload, and profit signals."],["Projects & rooms","Every address, room, finish, and scope detail."],["Wall measurements","Dimensions become auditable paintable area."],["Window & door detection","Openings are subtracted for accurate forecasts."],["Paint calculator","Coverage, coats, and waste become purchase quantities."],["AI recommendations","Missing scope and estimating risks are flagged."],["Material estimator","Quantities connect to retailer and supplier pricing."],["Labor estimator","Hours, crew size, and production rates stay visible."],["Crew management","Assign qualified people to the right work."],["Scheduling & calendar","Coordinate starts, milestones, and expectations."],["Customer management","Contacts, properties, notes, and history stay together."],["Quotes & invoices","Move approved scope from proposal to payment."],["Reporting & analytics","Learn what work, crews, and prices drive profit."],["Company settings & roles","Control defaults, permissions, and security."],["Integrations & AI assistant","Connect pricing, accounting, and workflows."]];

export function ProductTour({settingsMode=false}:{settingsMode?:boolean}){
 const [step,setStep]=useState(0); const [retailer,setRetailer]=useState<"Home Depot"|"Lowe's">("Home Depot");
 const gallons=paintGallons(88,400,2,10); const material=retailer==="Home Depot"?47.98:52.48; const labor=202.5; const total=(material+labor)/.55; const profit=total-material-labor;
 const steps=useMemo(()=>[
  {k:"Welcome",t:"Painting estimates that explain themselves.",b:"SmartCoat is built for painting companies. AI reviews scope, measurements, production assumptions, and margin signals so estimators catch omissions earlier, price consistently, and protect profit.",v:<div className="tour-hero"><Sparkles/><strong>AI estimate check</strong><span>2 openings accounted for · margin protected</span></div>},
  {k:"Create a project",t:"Start with the customer and the space.",b:"Create the customer, property address, project, rooms, and paint selections once. SmartCoat keeps those details connected from the first visit through the final invoice.",v:<div className="tour-fields">{["Customer · Morgan Reed","Address · 18 Oak Street","Project · Interior repaint","Room · Living Room","Paint · Behr, eggshell"].map(x=><div key={x}><Check size={16}/>{x}</div>)}</div>},
  {k:"Demonstration project",t:"Measure what will actually be painted.",b:"This 15′ × 8′ wall has 120 ft² of gross area. The 3′ × 4′ and 4′ × 5′ windows total 32 ft². SmartCoat subtracts those openings, leaving 88 ft² of paintable surface.",v:<div className="tour-equation"><span>120 ft²<small>wall area</small></span><b>−</b><span>32 ft²<small>windows</small></span><b>=</b><span className="accent">88 ft²<small>paintable</small></span></div>},
  {k:"Paint selection",t:"Tie coverage to the specified product.",b:"Manufacturer data makes coverage and coat assumptions explicit. Behr #N430-6A is demonstrated with a 400 ft²-per-gallon rate, eggshell sheen, and a primer review for color change and surface condition.",v:<div className="paint-card"><div className="swatch"/><div><strong>Behr · #N430-6A</strong><span>400 ft²/gal · Eggshell · 2 coats</span></div></div>},
  {k:"AI paint estimate",t:"Buy enough without overbuying.",b:`Two coats over 88 ft² with 10% waste requires ${gallons.calculated.toFixed(2)} gallons. SmartCoat recommends 1 gallon: a practical container quantity with a controlled waste allowance.`,v:<div className="metric-grid"><Metric l="Coverage" v="400 ft²/gal"/><Metric l="Calculated" v={`${gallons.calculated.toFixed(2)} gal`}/><Metric l="Purchase" v="1 gallon"/><Metric l="Waste" v="10%"/></div>},
  {k:"Store pricing",t:"Compare the material assumption.",b:"Choose a retailer to update the estimate. These are clearly marked demonstration prices; the adapter is ready for future retailer or supplier APIs.",v:<div><div className="retailer-toggle">{(["Home Depot","Lowe's"] as const).map(x=><button key={x} onClick={()=>setRetailer(x)} className={retailer===x?"active":""}>{x}</button>)}</div><p className="tour-price">${material.toFixed(2)} <small>placeholder / gallon</small></p></div>},
  {k:"Labor intelligence",t:"Turn production assumptions into a crew plan.",b:"The demonstration allows 4.5 labor hours at $45/hour. Completed projects will improve SmartCoat's labor hours, crew size, production rates, and margin recommendations over time.",v:<div className="metric-grid"><Metric l="Labor hours" v="4.5"/><Metric l="Crew plan" v="1 painter"/><Metric l="Loaded rate" v="$45/hr"/><Metric l="Labor cost" v="$202.50"/></div>},
  {k:"Project summary",t:"A professional estimate, ready to explain.",b:"Every number traces back to scope. That transparency makes estimates faster to review, easier to sell, and safer to hand off to production.",v:<div className="summary"><p><span>Customer</span>Morgan Reed</p><p><span>Room</span>Living Room · 15′ × 8′</p><p><span>Paint</span>Behr #N430-6A · 1 gal</p><p><span>Materials</span>${material.toFixed(2)}</p><p><span>Labor</span>${labor.toFixed(2)}</p><p><span>Estimated total</span><strong>${total.toFixed(2)}</strong></p><p><span>Gross profit</span><strong>${profit.toFixed(2)}</strong></p></div>},
  {k:"The SmartCoat platform",t:"One operating system for the painting company.",b:"Use each module when the job reaches that stage. Shared data removes duplicate entry, creates clean handoffs, and gives AI better context over time.",v:<div className="feature-grid">{features.map(([n,c])=><div key={n}><strong>{n}</strong><span>{c}</span></div>)}</div>}
 ],[gallons.calculated,labor,material,profit,retailer,total]);
 function finish(){localStorage.setItem("smartcoat.productTour.completed",new Date().toISOString());location.assign(settingsMode?"/dashboard":"/login?mode=signup");}
 return <main className="tour-shell"><div className="tour-topbar"><Link href={settingsMode?"/dashboard":"/"} className="tour-logo"><span>Smart</span>Coat</Link><button onClick={finish} className="tour-skip"><X size={16}/>Skip tour</button></div><div className="tour-progress"><span style={{width:`${((step+1)/9)*100}%`}}/></div><section className="tour-stage"><div className="tour-copy"><p className="tour-kicker">Step {step+1} of 9 · {steps[step].k}</p><h1>{steps[step].t}</h1><p className="tour-body">{steps[step].b}</p></div><div className="tour-visual" key={step}>{steps[step].v}</div></section><footer className="tour-controls"><button onClick={()=>setStep(s=>Math.max(0,s-1))} disabled={!step}><ArrowLeft size={18}/>Back</button><div>{steps.map((_,i)=><button aria-label={`Go to step ${i+1}`} key={i} onClick={()=>setStep(i)} className={i===step?"current":""}/>)}</div>{step<8?<button className="primary" onClick={()=>setStep(s=>s+1)}>Continue<ArrowRight size={18}/></button>:<button className="primary" onClick={finish}>Start SmartCoat<Check size={18}/></button>}</footer></main>;
}
function Metric({l,v}:{l:string,v:string}){return <div><span>{l}</span><strong>{v}</strong></div>}
