"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, RotateCcw, Sparkles, X } from "lucide-react";
import { calculateEstimate } from "@/lib/domain/estimate-engine";
import { getEstimatedRetailerPrice } from "@/lib/domain/retailer-pricing";
import { formatMoney } from "@/lib/domain/pricing";

type Demo={length:string;width:string;height:string;w1w:string;w1h:string;w2w:string;w2h:string;workers:string;wage:string;margin:number;retailer:"home_depot"|"lowes";zip:string;coats:number;coverage:number;waste:number};
const initial:Demo={length:"",width:"",height:"",w1w:"",w1h:"",w2w:"",w2h:"",workers:"",wage:"",margin:45,retailer:"home_depot",zip:"",coats:2,coverage:400,waste:10};
const num=(value:string)=>Number(value);

export function ProductTour({settingsMode=false}:{settingsMode?:boolean}){
 const [step,setStep]=useState(()=>{if(typeof window==="undefined")return 0;const saved=Number(localStorage.getItem("smartcoat.estimateTour.step"));return Number.isInteger(saved)&&saved>=0&&saved<10?saved:0}); const [form,setForm]=useState(initial); const [error,setError]=useState("");
 useEffect(()=>localStorage.setItem("smartcoat.estimateTour.step",String(step)),[step]);
 const pricing=useMemo(()=>getEstimatedRetailerPrice(form.retailer,/^\d{5}$/.test(form.zip)?form.zip:"00000"),[form.retailer,form.zip]);
 const result=useMemo(()=>{try{return calculateEstimate({room:{lengthFeet:num(form.length),widthFeet:num(form.width),heightFeet:num(form.height)},openings:[{kind:"window",widthFeet:num(form.w1w),heightFeet:num(form.w1h)},{kind:"window",widthFeet:num(form.w2w),heightFeet:num(form.w2h)}],coats:form.coats,coverageSqFtPerGallon:form.coverage,wastePercent:form.waste,paintPricePerGallonCents:pricing.pricePerGallonCents,productionRateSqFtPerHour:150,prepHours:2,crewSize:num(form.workers),averageWageCentsPerHour:Math.round(num(form.wage)*100),laborBurdenPercent:20,overheadPercent:10,targetGrossMarginPercent:form.margin,productiveHoursPerDay:8,retailer:form.retailer,zipCode:form.zip,pricingSource:pricing.source,pricingTimestamp:pricing.updatedAt})}catch{return null}},[form,pricing]);
 function patch<K extends keyof Demo>(key:K,value:Demo[K]){setForm(current=>({...current,[key]:value}));setError("")}
 function valid(){if(step===1&&![form.length,form.width,form.height].every(v=>num(v)>0))return "Enter all three room dimensions.";if(step===2&&![form.w1w,form.w1h,form.w2w,form.w2h].every(v=>num(v)>0))return "Enter both window dimensions.";if(step===4&&num(form.workers)<1)return "Choose at least one worker.";if(step===5&&num(form.wage)<=0)return "Enter an average hourly wage.";if(step===8&&!/^\d{5}$/.test(form.zip))return "Enter a valid five-digit ZIP code.";return ""}
 function next(){const message=valid();if(message)return setError(message);setStep(current=>Math.min(9,current+1))}
 function restart(){setForm(initial);setStep(0);setError("");localStorage.removeItem("smartcoat.estimateTour.step")}
 function finish(){localStorage.setItem("smartcoat.productTour.completed",new Date().toISOString());location.assign(settingsMode?"/dashboard":"/subscribe")}
 const inputClass="mt-2 min-h-12 w-full rounded-lg border border-border bg-white px-3 font-mono focus:border-brand";
 const screens=[
  <Panel key="welcome" title="Build one transparent room estimate." copy="SmartCoat calculates paint quantity, material and labor costs, crew duration, target margin, and a customer-ready price. This demo stays in your browser and never creates production records."><div className="tour-hero"><Sparkles/><strong>Ten guided steps</strong><span>You enter the scope. The shared SmartCoat engine explains every result.</span></div></Panel>,
  <Panel key="room" title="Enter the sample room." copy="Room perimeter × wall height = gross wall surface area. Accurate dimensions make paint and labor forecasts more reliable."><div className="tour-form-grid"><Field label="Length (ft)" value={form.length} onChange={v=>patch("length",v)} placeholder="15"/><Field label="Width (ft)" value={form.width} onChange={v=>patch("width",v)} placeholder="12"/><Field label="Wall height (ft)" value={form.height} onChange={v=>patch("height",v)} placeholder="8"/></div></Panel>,
  <Panel key="openings" title="Subtract two windows." copy="Openings are not paintable. Enter Window 1 as 3′ × 4′ and Window 2 as 4′ × 5′ to see the net area update."><div className="tour-form-grid"><Field label="Window 1 width" value={form.w1w} onChange={v=>patch("w1w",v)} placeholder="3"/><Field label="Window 1 height" value={form.w1h} onChange={v=>patch("w1h",v)} placeholder="4"/><Field label="Window 2 width" value={form.w2w} onChange={v=>patch("w2w",v)} placeholder="4"/><Field label="Window 2 height" value={form.w2h} onChange={v=>patch("w2h",v)} placeholder="5"/></div>,
  <div className="tour-equation"><span>{result?.grossSurfaceAreaSqFt??"—"} ft²<small>gross wall</small></span><b>−</b><span>{result?.deductedOpeningAreaSqFt??"—"} ft²<small>windows</small></span><b>=</b><span className="accent">{result?.netPaintableAreaSqFt??"—"} ft²<small>paintable</small></span></div></Panel>,
  <Panel key="paint" title="Specify the paint system." copy="The sample uses Behr color N430-6A. Coverage, sheen, coats, waste, and primer are explicit assumptions—not hidden guesses."><div className="paint-card"><div className="swatch"/><div><strong>Behr · N430-6A</strong><span>Premium Plus · Eggshell</span><span>400 ft²/gal · 2 coats · 10% waste</span><span>Primer: not included; inspect surface first</span></div></div></Panel>,
  <Panel key="crew" title="Choose the crew size." copy="Crew size changes elapsed duration, not total labor hours. Total labor hours ÷ workers = elapsed crew hours."><label className="block max-w-xs font-medium">Number of workers<input className={inputClass} type="number" min="1" max="20" value={form.workers} placeholder="2" onChange={e=>patch("workers",e.target.value)}/></label></Panel>,
  <Panel key="wage" title="Enter average worker pay." copy="Wage is not the full employer cost. SmartCoat adds a visible 20% demonstration labor burden for payroll taxes, insurance, and related costs."><label className="block max-w-xs font-medium">Average hourly wage ($)<input className={inputClass} type="number" min="1" step=".01" value={form.wage} placeholder="25" onChange={e=>patch("wage",e.target.value)}/></label></Panel>,
  <Panel key="margin" title="Set a true target gross margin." copy="SmartCoat uses customer price = contractor cost ÷ (1 − target margin). This is gross margin, not markup."><label className="block font-medium">Target gross margin <strong className="float-right text-brand">{form.margin}%</strong><input aria-label="Target gross margin percentage" className="mt-5 w-full accent-emerald-600" type="range" min="0" max="70" step="1" value={form.margin} onChange={e=>patch("margin",Number(e.target.value))}/></label></Panel>,
  <Panel key="retailer" title="Select a retailer." copy="No live retailer integration exists yet. These configurable figures are labeled estimated and can later be replaced by an approved API provider."><div className="retailer-toggle"><button onClick={()=>patch("retailer","home_depot")} className={form.retailer==="home_depot"?"active":""}>Home Depot</button><button onClick={()=>patch("retailer","lowes")} className={form.retailer==="lowes"?"active":""}>Lowe&apos;s</button></div><p className="tour-price">{formatMoney(pricing.pricePerGallonCents)}<small>estimated per gallon · configured {pricing.updatedAt.slice(0,10)}</small></p></Panel>,
  <Panel key="zip" title="Enter the project ZIP code." copy="ZIP is validated and carried with the pricing assumption. Current prices are not location-specific, so SmartCoat will not claim they are local."><label className="block max-w-xs font-medium">Five-digit ZIP code<input aria-describedby="zip-note" className={inputClass} inputMode="numeric" maxLength={5} value={form.zip} placeholder="33601" onChange={e=>patch("zip",e.target.value.replace(/\D/g,"").slice(0,5))}/></label><p id="zip-note" className="mt-3 text-sm text-muted">Regional lookup: coming soon. Estimated pricing is used safely.</p></Panel>,
  <Panel key="result" title="Your sample estimate is complete." copy="Unlock SmartCoat Premium to create, save, compare, export, and manage real customer estimates."><Result result={result} form={form}/><div className="mt-6 grid gap-3 sm:grid-cols-2"><Link href="/subscribe" className="inline-flex min-h-12 items-center justify-center rounded-lg bg-brand px-5 font-semibold text-white">Subscribe to SmartCoat Premium</Link><button onClick={restart} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-lg border border-border font-semibold"><RotateCcw size={18}/>Restart Tour</button><button onClick={()=>setStep(8)} className="min-h-12 rounded-lg border border-border font-semibold">Review the Estimate</button><Link href="/dashboard" className="inline-flex min-h-12 items-center justify-center rounded-lg border border-border font-semibold">Return to Locked Dashboard</Link></div></Panel>
 ];
 return <main className="tour-shell"><div className="tour-topbar"><Link href="/" className="tour-logo"><span>Smart</span>Coat</Link><button onClick={finish} className="tour-skip"><X size={16}/>Skip tour</button></div><div className="tour-progress"><span style={{width:`${((step+1)/10)*100}%`}}/></div><section className="tour-stage"><div className="tour-copy"><p className="tour-kicker">Interactive estimate · Step {step+1} of 10</p><h1>{step===0?"Welcome to SmartCoat":step===9?"Estimate generated":"Your inputs drive the math"}</h1><p className="tour-body">Demo mode is isolated from customer records, reporting, and analytics.</p></div><div className="tour-visual" key={step}>{screens[step]}{error&&<p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}</div></section><footer className="tour-controls"><button onClick={()=>setStep(s=>Math.max(0,s-1))} disabled={!step}><ArrowLeft size={18}/>Back</button><div>{screens.map((_,i)=><button aria-label={`Go to step ${i+1}`} key={i} onClick={()=>i<step&&setStep(i)} className={i===step?"current":""}/>)}</div>{step<9?<button className="primary" onClick={next}>{step===0?"Start Tour":"Continue"}<ArrowRight size={18}/></button>:<button className="primary" onClick={finish}>Done<Check size={18}/></button>}</footer></main>
}
function Panel({title,copy,children}:{title:string;copy:string;children:React.ReactNode}){return <div><h2 className="text-2xl font-semibold">{title}</h2><p className="mb-6 mt-2 leading-7 text-muted">{copy}</p>{children}</div>}
function Field({label,value,onChange,placeholder}:{label:string;value:string;onChange:(value:string)=>void;placeholder:string}){return <label className="text-sm font-medium">{label}<input className="mt-2 min-h-12 w-full rounded-lg border border-border px-3 font-mono" type="number" min="0" step=".01" value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
function Result({result,form}:{result:ReturnType<typeof calculateEstimate>|null;form:Demo}){if(!result)return <p role="alert" className="rounded-lg bg-amber-50 p-4">Complete the required inputs to generate the estimate.</p>;const rows=[["Gross wall area",`${result.grossSurfaceAreaSqFt} ft²`],["Window area",`${result.deductedOpeningAreaSqFt} ft²`],["Net paintable area",`${result.netPaintableAreaSqFt} ft²`],["Coverage with coats + waste",`${result.adjustedCoverageSqFt} ft²`],["Paint required",`${result.rawGallonsRequired} gal`],["Recommended purchase",`${result.recommendedGallons} gal`],["Paint","Behr N430-6A · Eggshell"],["Retailer",form.retailer==="home_depot"?"Home Depot":"Lowe's"],["ZIP",form.zip],["Estimated material cost",formatMoney(result.materialSubtotalCents)],["Total labor hours",`${result.laborHours} hours`],["Crew / duration",`${result.crewSize} workers · ${result.estimatedWorkingDays} days`],["Wages",formatMoney(result.wageCostCents)],["Labor burden",formatMoney(result.laborBurdenCents)],["Total contractor cost",formatMoney(result.totalContractorCostCents)],["Target gross margin",`${result.targetGrossMarginPercent}%`],["Customer estimate",formatMoney(result.customerEstimateCents)],["Expected gross profit",formatMoney(result.expectedGrossProfitCents)]];return <div className="summary">{rows.map(([l,v])=><p key={l}><span>{l}</span><strong>{v}</strong></p>)}<p className="rounded-lg bg-amber-50 p-3 text-xs text-amber-900">{result.warnings.join(" ")}</p></div>}
