"use client";
import { useState } from "react";
import { createClient } from "@/lib/supabase/browser";

export function ProgressEditor({estimateId,initialStatus,initialPercent,initialNotes}:{estimateId:string;initialStatus:string;initialPercent:number;initialNotes:string}){
  const [status,setStatus]=useState(initialStatus); const [percent,setPercent]=useState(String(initialPercent)); const [notes,setNotes]=useState(initialNotes); const [message,setMessage]=useState("");
  async function save(){setMessage("Saving…");const value=Math.max(0,Math.min(100,Number(percent)||0));const {error}=await createClient().from("estimate_progress").update({status,completion_percent:value,progress_notes:notes,updated_at:new Date().toISOString()}).eq("estimate_id",estimateId);if(error){console.error("progress_update_failed",{code:error.code});setMessage(error.message)}else setMessage("Progress saved. Approved pricing was not recalculated.");}
  return <section className="rounded-xl border border-border bg-surface p-5"><h2 className="text-xl font-semibold">Project Progress</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Status<select value={status} onChange={e=>setStatus(e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border px-3">{["not_started","prep","in_progress","final_coat","touch_ups","completed","blocked"].map(value=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select></label><label className="text-sm font-medium">Completion percentage<input value={percent} onChange={e=>setPercent(e.target.value)} inputMode="numeric" className="mt-1 min-h-11 w-full rounded-lg border px-3"/></label></div><label className="mt-4 block text-sm font-medium">Progress notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} className="mt-1 min-h-24 w-full rounded-lg border p-3"/></label><button onClick={save} className="mt-4 min-h-11 rounded-lg bg-brand px-4 font-semibold text-white">Update Progress</button>{message&&<p role="status" className="mt-2 text-sm">{message}</p>}</section>;
}
