-- SmartCoat foundation: tenant ownership, RBAC, immutable estimate snapshots, and auditability.
create extension if not exists pgcrypto;
create schema if not exists private;

create type public.company_role as enum ('owner','admin','manager','estimator','crew_leader','worker');
create type public.membership_status as enum ('invited','active','suspended');
create type public.estimate_status as enum ('draft','sent','accepted','rejected','expired','converted');
create type public.project_status as enum ('planned','active','blocked','inspection','complete','cancelled');

create table public.companies (
  id uuid primary key default gen_random_uuid(), name text not null check (char_length(name) between 2 and 160),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'), timezone text not null default 'America/New_York',
  currency char(3) not null default 'USD', default_tax_basis_points integer not null default 0 check (default_tax_basis_points between 0 and 10000),
  default_margin_basis_points integer not null default 4500 check (default_margin_basis_points between 0 and 9900),
  onboarding_completed_at timestamptz, suspended_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, phone text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.company_memberships (
  company_id uuid not null references public.companies(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade,
  role public.company_role not null, status public.membership_status not null default 'active', created_at timestamptz not null default now(), primary key(company_id,user_id)
);
create index memberships_user_active_idx on public.company_memberships(user_id,company_id) where status='active';

create table public.customers (
  id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete restrict, type text not null default 'individual' check(type in('individual','company')),
  name text not null, email text, phone text, status text not null default 'lead', notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz
);
create index customers_company_name_idx on public.customers(company_id,name) where archived_at is null;
create table public.properties (
  id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete restrict, customer_id uuid not null references public.customers(id) on delete restrict,
  name text not null, address_line_1 text not null, city text not null, region text not null, postal_code text not null, access_notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index properties_company_customer_idx on public.properties(company_id,customer_id);

create table public.estimates (
  id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete restrict, customer_id uuid references public.customers(id) on delete restrict, property_id uuid references public.properties(id) on delete restrict,
  estimate_number bigint generated by default as identity, title text not null, status public.estimate_status not null default 'draft', version integer not null default 1 check(version>0),
  cost_cents bigint not null default 0 check(cost_cents>=0), subtotal_cents bigint not null default 0 check(subtotal_cents>=0), tax_cents bigint not null default 0 check(tax_cents>=0), total_cents bigint not null default 0 check(total_cents>=0),
  target_margin_percent numeric(5,2) not null default 45 check(target_margin_percent>=0 and target_margin_percent<100), calculation_snapshot jsonb not null default '{}'::jsonb,
  created_by uuid not null default auth.uid() references auth.users(id), accepted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(company_id,estimate_number)
);
create index estimates_company_status_created_idx on public.estimates(company_id,status,created_at desc);
create table public.estimate_rooms (
  id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete restrict, estimate_id uuid not null references public.estimates(id) on delete cascade,
  name text not null, sort_order integer not null default 0, length_millifeet integer not null check(length_millifeet>0), width_millifeet integer not null check(width_millifeet>0), height_millifeet integer not null check(height_millifeet>0),
  doors integer not null default 0 check(doors>=0), windows integer not null default 0 check(windows>=0), calculation_snapshot jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create index estimate_rooms_tenant_estimate_idx on public.estimate_rooms(company_id,estimate_id);

create table public.projects (
  id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete restrict, estimate_id uuid not null references public.estimates(id) on delete restrict,
  name text not null, status public.project_status not null default 'planned', contract_snapshot jsonb not null, starts_on date, ends_on date, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(company_id,estimate_id)
);
create index projects_company_status_idx on public.projects(company_id,status);
create table public.employees (
  id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete restrict, user_id uuid references auth.users(id) on delete set null,
  name text not null, job_title text, employment_status text not null default 'active', loaded_rate_cents integer check(loaded_rate_cents>=0), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.invoices (
  id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete restrict, project_id uuid not null references public.projects(id) on delete restrict,
  invoice_number bigint generated by default as identity, status text not null default 'draft', total_cents bigint not null check(total_cents>=0), balance_cents bigint not null check(balance_cents>=0), issued_at timestamptz, due_at timestamptz, created_at timestamptz not null default now(), unique(company_id,invoice_number)
);
create table public.payments (
  id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete restrict, invoice_id uuid not null references public.invoices(id) on delete restrict,
  amount_cents bigint not null check(amount_cents>0), provider text, provider_reference text, status text not null, received_at timestamptz, created_at timestamptz not null default now(), unique(provider,provider_reference)
);
create table public.audit_logs (
  id bigint generated always as identity primary key, company_id uuid references public.companies(id) on delete restrict, actor_id uuid references auth.users(id) on delete set null,
  action text not null, entity_type text not null, entity_id text, metadata jsonb not null default '{}'::jsonb, occurred_at timestamptz not null default now()
);
create index audit_logs_company_time_idx on public.audit_logs(company_id,occurred_at desc);

create function private.is_company_member(target_company uuid) returns boolean language sql stable security invoker set search_path='' as $$
  select exists(select 1 from public.company_memberships m where m.company_id=target_company and m.user_id=(select auth.uid()) and m.status='active')
$$;
create function private.has_company_role(target_company uuid, allowed public.company_role[]) returns boolean language sql stable security invoker set search_path='' as $$
  select exists(select 1 from public.company_memberships m where m.company_id=target_company and m.user_id=(select auth.uid()) and m.status='active' and m.role=any(allowed))
$$;
revoke all on all functions in schema private from public, anon;
grant usage on schema private to authenticated;
grant execute on function private.is_company_member(uuid), private.has_company_role(uuid,public.company_role[]) to authenticated;

alter table public.companies enable row level security; alter table public.profiles enable row level security; alter table public.company_memberships enable row level security;
alter table public.customers enable row level security; alter table public.properties enable row level security; alter table public.estimates enable row level security; alter table public.estimate_rooms enable row level security;
alter table public.projects enable row level security; alter table public.employees enable row level security; alter table public.invoices enable row level security; alter table public.payments enable row level security; alter table public.audit_logs enable row level security;

create policy companies_read on public.companies for select to authenticated using (private.is_company_member(id));
create policy memberships_read on public.company_memberships for select to authenticated using (private.is_company_member(company_id));
create policy profiles_self_read on public.profiles for select to authenticated using (id=(select auth.uid()));
create policy profiles_self_update on public.profiles for update to authenticated using (id=(select auth.uid())) with check(id=(select auth.uid()));
create policy customers_read on public.customers for select to authenticated using(private.is_company_member(company_id));
create policy customers_write on public.customers for all to authenticated using(private.has_company_role(company_id,array['owner','admin','manager','estimator']::public.company_role[])) with check(private.has_company_role(company_id,array['owner','admin','manager','estimator']::public.company_role[]));
create policy properties_read on public.properties for select to authenticated using(private.is_company_member(company_id));
create policy properties_write on public.properties for all to authenticated using(private.has_company_role(company_id,array['owner','admin','manager','estimator']::public.company_role[])) with check(private.has_company_role(company_id,array['owner','admin','manager','estimator']::public.company_role[]));
create policy estimates_read on public.estimates for select to authenticated using(private.is_company_member(company_id));
create policy estimates_write on public.estimates for all to authenticated using(private.has_company_role(company_id,array['owner','admin','manager','estimator']::public.company_role[])) with check(private.has_company_role(company_id,array['owner','admin','manager','estimator']::public.company_role[]));
create policy estimate_rooms_access on public.estimate_rooms for all to authenticated using(private.is_company_member(company_id)) with check(private.has_company_role(company_id,array['owner','admin','manager','estimator']::public.company_role[]));
create policy projects_read on public.projects for select to authenticated using(private.is_company_member(company_id));
create policy projects_manage on public.projects for all to authenticated using(private.has_company_role(company_id,array['owner','admin','manager']::public.company_role[])) with check(private.has_company_role(company_id,array['owner','admin','manager']::public.company_role[]));
create policy employees_read on public.employees for select to authenticated using(private.has_company_role(company_id,array['owner','admin','manager']::public.company_role[]) or user_id=(select auth.uid()));
create policy employees_manage on public.employees for all to authenticated using(private.has_company_role(company_id,array['owner','admin']::public.company_role[])) with check(private.has_company_role(company_id,array['owner','admin']::public.company_role[]));
create policy invoices_access on public.invoices for all to authenticated using(private.has_company_role(company_id,array['owner','admin','manager']::public.company_role[])) with check(private.has_company_role(company_id,array['owner','admin','manager']::public.company_role[]));
create policy payments_access on public.payments for select to authenticated using(private.has_company_role(company_id,array['owner','admin','manager']::public.company_role[]));
create policy audits_read on public.audit_logs for select to authenticated using(private.has_company_role(company_id,array['owner','admin']::public.company_role[]));

-- Explicit grants are required for new Supabase projects as of May 2026; RLS remains the authorization layer.
grant select on public.companies, public.company_memberships, public.profiles, public.customers, public.properties, public.estimates, public.estimate_rooms, public.projects, public.employees, public.invoices, public.payments, public.audit_logs to authenticated;
grant insert,update,delete on public.customers, public.properties, public.estimates, public.estimate_rooms, public.projects, public.employees, public.invoices to authenticated;
grant update on public.profiles to authenticated;
grant usage,select on all sequences in schema public to authenticated;

create function private.set_updated_at() returns trigger language plpgsql security invoker set search_path='' as $$ begin new.updated_at=now(); return new; end $$;
create trigger companies_updated before update on public.companies for each row execute function private.set_updated_at();
create trigger customers_updated before update on public.customers for each row execute function private.set_updated_at();
create trigger properties_updated before update on public.properties for each row execute function private.set_updated_at();
create trigger estimates_updated before update on public.estimates for each row execute function private.set_updated_at();
create trigger projects_updated before update on public.projects for each row execute function private.set_updated_at();
revoke all on function private.set_updated_at() from public,anon,authenticated;
